### ISSUE TITLE
Symlink target used for EL systems

### ISSUE THREAD

**Issue by treydock** [ghoneycutt/puppet-module-pam#117]
Right now the symlink created for system-auth points to /etc/pam.d/system-auth-ac.  The default behavior of EL systems is that the symlink be relative so

```
lrwxrwxrwx. 1 root root 14 Apr  7 13:37 /etc/pam.d/system-auth -> /etc/pam.d/system-auth-ac
```

Should be

```
lrwxrwxrwx. 1 root root 14 Apr  7 13:37 /etc/pam.d/system-auth -> system-auth-ac
```

The way I've handled that in my fork has been to make the target a parameter.  So `$system_auth_target => 'system-auth-ac'`.  It seems like a more elegant solution may be to make the default `undef` and have the real value be something like this

```
$system_auth_target_real = pick($system_auth_target, basename($system_auth_ac_file))
```

The only issue with using `basename()` is that it requires stdlib >= 4.6.0.

This kind of change is really just a 'nit-pick' since it has no impact on functionality that I'm aware of.  My main motivation is to just remove unnecessary changes being made by puppet to a default system install.

Somewhat relates to #97 because the same would need to be done for the symlink of password-auth -> password-auth-ac.

**Comment by ghoneycutt** [comment]
I've been slowly moving all the modules to use stdlib 4.6.0, which is needed to support Puppet v4 and it is also compatible with Puppet v3, so that's OK.

The design principal here is that if you were to apply this module on a freshly installed stock system, that no changes would occur. It seems that the symlink being fully pathed instead of relative is not the default for EL. I like your approach using pick().

Could you send me a PR?

It would need to have the new parameter in the README, validation of the parameter (`validate_string()` since we don't know if it is relative or not), and corresponding spec tests that show the default behavior, what happens if you set the parameter, and that failure occurs if using an invalid type.

**Comment by treydock** [comment]
@ghoneycutt I'd be happy to open a PR.  I will have to wait till #97 is merged as that PR matches the current behavior of how system-auth is handled so may be cleaner to make the symlink change once both password-auth/password-auth-ac and system-auth/system-auth-ac are managed.

**Comment by ghoneycutt** [comment]
We have released a new major version of this module and greatly appreciate your efforts. Please consider using the new version which supports Puppet 5 and 6.

@treydock please re-open if this is still an issue.
