### ISSUE TITLE
Missing pam_fprintd.so

### ISSUE THREAD

**Issue by hdep** [ghoneycutt/puppet-module-pam#198]
Hello,

on my system I got the following error in /var/log/secure : 

```
passwd: PAM unable to dlopen(/usr/lib64/security/pam_fprintd.so): /usr/lib64/security/pam_fprintd.so: Ne peut ouvrir le fichier d'objet partag▒: Aucun fichier ou dossier de ce type
 passwd: PAM adding faulty module: /usr/lib64/security/pam_fprintd.so
```

Looking in my system I don't have any rpm installed for this file. Am I the only one having this issue ? 
Should we enforce the installation of this package fprintd-pam.x86_64 ?

**Comment by ghoneycutt** [comment]
Confirmed with the EL7 vagrant system.

**Comment by ghoneycutt** [comment]
Thanks for bringing this up!

I don't think we should enable this by default as the system works fine despite the messages. Also when you install fprintd-pam it installs fprintd which is another running service and is only useful if you have a finger print reader, which does not apply to the majority of systems.

If you want this functionality, the fix is to simply install the `fprintd-pam` package.
