### ISSUE TITLE
Ability to run only certain 'submodules' so that one can ease into the PAM management more slowly.

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-pam#250]
I'd like to implement the limits.d functionality of this module but I don't want to dive into the management of /etc/pam.d files yet.

I've put together a hackish proof of concept of specifying only 'submodule' of this module to run located [here](https://github.com/bschonec/puppet-module-pam/tree/suppress_running_of_selected_modules) with the changes [here](https://github.com/bschonec/puppet-module-pam/pull/1/files)
I admit that I'm no developer but I'd like to get feedback about implementing the proposed feature.

**Comment by ghoneycutt** [comment]
This very creative though not a great pattern for consuming public modules. An easier approach to using this module would be to take a system with a PAM configuration you like and then just copy the contents of each file into Hiera using the appropriate parameters and convert the lines into a YAML array. Then you can test and be sure that the module is not actually changing anything other than adding some comments to the files. This way you can use the module as it is intended instead of going through such lengths to skip sections. Those will not be easy for anyone to maintain.
